# Generated by Django 5.2.5 on 2025-08-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_rename_user_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='liked_book_indices',
            field=models.CharField(),
        ),
    ]
